version: '3.7'
services:
  api:
    image: node:14.15.1
    container_name: otrium_api
    working_dir: /var/workspace
    ports:
      - 5000:3000
    env_file:
      - .env
      - .env.development
    volumes:
      - ./:/var/workspace
    networks:
      - otriumnet
    command: sleep infinity
  db:
    image: mysql:8.0
    container_name: otrium_db
    ports:
      - 3306:3306
    env_file:
      - .env
      - .env.development
    volumes:
      - ~/ddata/otrium/development/db:/var/lib/mysql
    networks:
      - otriumnet
    command: --default-authentication-plugin=mysql_native_password

networks:
  otriumnet:
    external: true
